import { EditorCore } from "./editorCore.js";

const editor = new EditorCore({ fps: 30, duration: 120 });
editor.state.tracks = [{ id: "v1", name: "Video", type: "video", visible: true, locked: false, order: 0 }];
editor.state.clips = [{ id: "c1", name: "Clip", trackId: "v1", start: 1, duration: 10, in: 0, out: 10, transform: { scale: 1, rotate: 0 }, opacity: 1, blendMode: "normal", keyframes: [], transitions: [], audio: { volume: 1, fadeIn: 0, fadeOut: 0 }, freezeFrames: [] }];

editor.addTrack({ id: "v2", name: "B-roll", type: "video", order: 1 });
editor.addTrack({ id: "a1", name: "Voice", type: "audio", order: 2 });
editor.addClip({ id: "aClip", name: "Voice", type: "audio", trackId: "a1", start: 0, duration: 20 });
editor.selectClip("c1");
editor.moveClip("c1", 2);
editor.moveClipToTrack("c1", "v2", 2.5);
editor.reorderClip("c1", 4);
editor.trimClipStart("c1", 3);
editor.trimClipEnd("c1", 6);
editor.trimClipEnd("c1", 7, { ripple: true });
editor.seek(4);
editor.splitSelected();
editor.copySelected();
editor.paste(12);
editor.duplicateSelected();
editor.groupSelected();
editor.setSpeed(1.25);
editor.reverseSelected();
editor.freezeFrameSelected();
editor.transformSelected({ rotate: 12, scale: 1.1, flipX: true, flipY: true, crop: { x: 0, y: 0, width: 1, height: 1 } });
editor.setOpacity(0.75);
editor.setBlendMode("screen");
editor.addKeyframe("position", { x: 10, y: 20 });
editor.addTransition("video", 0.5, "cross-dissolve");
editor.setAudio({ volume: 0.8, fadeIn: 0.2, fadeOut: 0.3 });
editor.setMute(false);
editor.setSolo(false);
editor.setEffect("blur", { radius: 8 });
editor.setTrackAudio("a1", { muted: false, solo: true });
editor.setCanvasZoom(1.25);
editor.setPlaybackRate(1.5);
editor.setPlaying(true);
editor.tick(1000);
editor.tick(1033);
editor.setPlaying(false);
const frame = editor.renderFrame(4);
editor.deleteSelected({ ripple: true });
editor.undo();
editor.redo();

if (!editor.state.history.length) throw new Error("history was not recorded");
if (!Array.isArray(editor.previewFrame())) throw new Error("preview frame did not return an array");
if (!Array.isArray(frame.layers) || !Array.isArray(frame.audio)) throw new Error("render frame did not compose layers");
if (!frame.gpuHints?.preferCompositor) throw new Error("render frame did not expose gpu hints");
