import { useAuthStore } from '../../auth-store';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpRight, Bookmark, ChevronLeft, ChevronRight, Download, Globe2, LoaderCircle, Package, Search, SlidersHorizontal, Users, X } from 'lucide-react';
import { Creator, Market, Period, markets, money, number, safeUrl, searchCreators, normalizeUsername, CreatorRequestError, validUsername } from './creator-api';
import './creator-explorer.css';

type Filters = { category: string; revenue: string; followers: string; engagement: string; averageViews: string; growth: string };
const defaults: Filters = {category:'',revenue:'',followers:'',engagement:'',averageViews:'',growth:''};
const filterDefinitions = [
  {key:'category',label:'Product category',options:[['','All categories'],['Beauty','Beauty'],['Fashion','Fashion'],['Home','Home'],['Food & Drinks','Food & Drinks'],['Electronics','Electronics'],['Fitness','Fitness']]},
  {key:'revenue',label:'Revenue / GMV',options:[['','Any revenue'],['1000','1,000+'],['10000','10,000+'],['100000','100,000+']]},
  {key:'growth',label:'Revenue trend',options:[['','Any trend'],['up','Growing'],['down','Declining']]},
  {key:'followers',label:'Followers',options:[['','Any audience size'],['10000','10K+'],['50000','50K+'],['100000','100K+'],['1000000','1M+']]},
  {key:'engagement',label:'Engagement rate',options:[['','Any engagement'],['1','1%+'],['3','3%+'],['5','5%+'],['10','10%+']]},
  {key:'averageViews',label:'Average video views',options:[['','Any view count'],['1000','1K+'],['10000','10K+'],['100000','100K+']]}
] as const;
function fits(c: Creator, f: Filters, period: Period) {
  const m=c.analytics[period]?.metrics;
  if(f.category && c.niche?.toLowerCase()!==f.category.toLowerCase() && !c.analytics[period]?.categories.some(x=>x.name.toLowerCase()===f.category.toLowerCase()))return false;
  for(const [key,value] of [['revenue',m?.revenue],['followers',c.followers],['engagement',m?.engagementRate],['averageViews',m?.averageViews]] as const)if(f[key] && (typeof value!=='number'||value<Number(f[key])))return false;
  if(f.growth && (typeof m?.growth!=='number'||(f.growth==='up'?m.growth<=0:m.growth>=0)))return false;
  return true;
}
function Trend({creator,period}:{creator:Creator;period:Period}) {
  const points=(creator.analytics[period]?.series||[]).filter(p=>typeof p.revenue==='number'&&Number.isFinite(p.revenue)).sort((a,b)=>a.date.localeCompare(b.date));
  if(points.length<2)return <span className="directory-missing">—</span>;
  const max=Math.max(1,...points.map(p=>p.revenue!));
  return <svg width="98" height="32" viewBox="0 0 98 32" role="img" aria-label="Revenue trend"><polyline fill="none" stroke="#3f8b78" strokeWidth="2" points={points.map((p,i)=>`${i/(points.length-1)*96+1},${30-p.revenue!/max*28}`).join(' ')}/></svg>;
}
function CreatorSignIn({onSuccess}:{onSuccess:()=>void}) {
  const signIn=useAuthStore(s=>s.signIn);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  return <form className="directory-search" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const result=await signIn(email,password);if(result.error)setMessage(result.error.message);else onSuccess();}finally{setBusy(false);setPassword('');}}}>
    <label className="directory-query"><span>Email</span><div><input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></div></label>
    <label className="directory-query"><span>Password</span><div><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></div></label>
    <button className="research-primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button>{message&&<p role="alert">{message}</p>}
  </form>;
}
export function CreatorExplorer({onOpen,onHistory,saved,onSave}:{onOpen:(c:Creator,p:Period)=>void;onHistory:(username:string,market:Market)=>void;saved:Creator[];onSave:(c:Creator)=>void}) {
  useEffect(()=>{const previous=document.title;document.title='Search Creator API';return ()=>{document.title=previous;};},[]);
  const [market,setMarket]=useState<Market|''>('GB');const [query,setQuery]=useState('');const [period,setPeriod]=useState<Period>(30);
  const [draft,setDraft]=useState<Filters>(defaults);const [applied,setApplied]=useState<Filters>(defaults);
  const [rows,setRows]=useState<Creator[]>([]);const [status,setStatus]=useState('idle');const [sort,setSort]=useState('revenue');const [ascending,setAscending]=useState(false);const [page,setPage]=useState(1);const [size,setSize]=useState(20);const [onlySaved,setOnlySaved]=useState(false);
  const [hasMore,setHasMore]=useState(false); const [error,setError]=useState(''); const [stale,setStale]=useState(false);
  const activeRequest=useRef<AbortController|null>(null);
  useEffect(()=>()=>activeRequest.current?.abort(),[]);
  function invalidate(){activeRequest.current?.abort();setRows([]);setStatus('idle');setError('');setStale(false);setHasMore(false);setPage(1);}
  async function search(f=applied,nextPage=1,pageSize=size) {
    if(!market || !validUsername(query)){setStatus('invalid');setError('Enter a TikTok creator username or profile URL.');return;}
    activeRequest.current?.abort();const controller=new AbortController();activeRequest.current=controller;
    setStatus('loading');setError('');setRows([]);setHasMore(false);setStale(false);setPage(nextPage);
    const timer=setTimeout(()=>{controller.abort();if(activeRequest.current===controller){setStatus('unavailable');setError('The request timed out. Please try again.');}},15000);
    try {
      const result=await searchCreators(query,market,period,nextPage,pageSize,controller.signal);if(controller.signal.aborted)return;
      setRows(result.creators);setStatus(result.creators.length?'found':'not_found');setHasMore(result.pagination.hasMore);setStale(result.stale);
      onHistory(normalizeUsername(query),market);
    }catch(error){if(!controller.signal.aborted){setStatus(error instanceof CreatorRequestError?error.code.toLowerCase():'unavailable');setError(error instanceof CreatorRequestError?error.message:'Unable to load creator data. Please try again.');}}finally{clearTimeout(timer);}
  }
  const filtered=useMemo(()=>rows.filter(c=>c.market===market&&fits(c,applied,period)&&(!onlySaved||saved.some(s=>s.market===c.market&&s.username===c.username))).sort((a,b)=>{
    const get=(c:Creator)=>sort==='followers'?c.followers:c.analytics[period]?.metrics[sort as keyof NonNullable<Creator['analytics'][30]>['metrics']];const av=get(a),bv=get(b);
    if(typeof av!=='number')return typeof bv==='number'?1:0;if(typeof bv!=='number')return -1;return ascending?av-bv:bv-av;
  }),[rows,market,applied,period,onlySaved,saved,sort,ascending]);
  const currentPage=page;const visible=filtered;
  function sortBy(key:string){if(sort===key)setAscending(!ascending);else{setSort(key);setAscending(false);}}
  function exportRows(){const escape=(v:unknown)=>`"${String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')}"`;const csv=[['Username','Market','Period days','Revenue','Items sold','Followers','Growth percent','Views','Engagement percent'],...filtered.map(c=>{const m=c.analytics[period]?.metrics;return [c.username,c.market,period,m?.revenue,m?.itemsSold,c.followers,m?.growth,m?.views,m?.engagementRate];})].map(r=>r.map(escape).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`launchly-creators-${market}-${period}d.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const activeFilters=Object.entries(applied).filter(([,v])=>v);
  const headers=[['Creator',''],['Revenue / GMV','revenue'],['Items sold','itemsSold'],['Followers','followers'],['Revenue growth','growth'],['Promoted products',''],['Revenue trend',''],['Content views','views'],['Engagement','engagementRate'],['Action','']];
  return <div className="creator-directory"><div className="directory-heading"><div><h1>Search Creator API</h1><p>Search TikTok Shop creators and view real creator analytics.</p></div><span><Globe2 size={14}/> Launchly Creator API</span></div>
    <form className="directory-search" onSubmit={e=>{e.preventDefault();search();}}><label className="directory-market"><span>Market</span><select aria-label="Creator market" required value={market} onChange={e=>{invalidate();setMarket(e.target.value as Market);}}><option value="" disabled>Select country</option>{Object.entries(markets).map(([code,m])=><option key={code} value={code}>{m.flag} {m.name}</option>)}</select></label><label className="directory-query"><span>Search TikTok creator username</span><div><Search size={18}/><input placeholder="Search username or @creator" maxLength={512} aria-label="Search TikTok creator username" disabled={!market} value={query} onChange={e=>{invalidate();setQuery(e.target.value);}}/>{query&&<button type="button" aria-label="Clear username" onClick={()=>{invalidate();setQuery('');}}><X size={15}/></button>}</div></label><button className="research-primary" disabled={!market||status==='loading'||!validUsername(query)}>{status==='loading'?<LoaderCircle className="spin" size={16}/>:<Search size={16}/>} {status==='loading'?'Searching creator data...':'Search Creator'}</button></form>
    {period>30&&<p className="directory-filter-note">For this period, enter an exact @username or TikTok profile URL.</p>}
    {stale&&<div className="research-notice" role="status">Showing recently cached data while live updates are unavailable.</div>}
    {error&&<div className="research-notice" role="alert">{error} {status==='subscription_required'&&<a href="/pricing">View plans</a>}</div>}
    {status==='unauthorized'&&<CreatorSignIn onSuccess={()=>search()}/>}
    <div className="directory-layout"><aside className="directory-filters"><div className="directory-filter-title"><h2><SlidersHorizontal size={16}/> Filters</h2><button onClick={()=>{setDraft(defaults);setApplied(defaults);}}>Reset</button></div><fieldset disabled={!market}><label className="directory-period">Time period<select aria-label="Time period" value={period} onChange={e=>{invalidate();setPeriod(Number(e.target.value) as Period);}}>{([7,30,90,180,365] as Period[]).map(p=><option key={p} value={p}>{p===365?'Last 1 year':`Last ${p} days`}</option>)}</select></label>{filterDefinitions.map((f,i)=><React.Fragment key={f.key}>{i===1&&<h3>SHOP PERFORMANCE</h3>}{i===3&&<h3>CREATOR AUDIENCE</h3>}<label>{f.label}<select disabled={!['revenue','followers'].includes(f.key)} title={!['revenue','followers'].includes(f.key)?'This metric is not available in creator search results':undefined} value={draft[f.key]} onChange={e=>setDraft({...draft,[f.key]:e.target.value})}>{f.options.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></React.Fragment>)}<button className="research-primary directory-apply" onClick={()=>{setApplied({...draft});setPage(1);search(draft);}} disabled={status==='loading'}>Apply filters</button></fieldset><p className="directory-filter-note"><Globe2 size={13}/>{market?`Only ${markets[market].name} creators`:'Select a market to start'}</p></aside>
    <section className="directory-results"><div className="directory-result-toolbar"><div className="directory-tabs"><button className={!onlySaved?'selected':''} onClick={()=>{setOnlySaved(false);}}>Creators <span>{status==='found'?filtered.length:'—'}</span></button><button className={onlySaved?'selected':''} onClick={()=>{setOnlySaved(true);}}><Bookmark size={14}/> Saved matches</button></div><button className="directory-export" disabled={!filtered.length} onClick={exportRows}><Download size={14}/> Export</button></div><div className="directory-applied"><span>{period===365?'Last 1 year':`Last ${period} days`}</span>{market&&<span>{markets[market].flag} {markets[market].name}</span>}{activeFilters.map(([key,value])=><button key={key} onClick={()=>{setApplied({...applied,[key]:''});setDraft({...draft,[key]:''});}}>{filterDefinitions.find(f=>f.key===key)?.label}: {value}<X size={11}/></button>)}<small>{activeFilters.length?`${activeFilters.length} filters applied`:'Filters and sorting apply to this result page'}</small></div>
    <div className="directory-table-scroll"><table className="directory-table"><thead><tr><th>#</th>{headers.map(([label,key])=><th key={label} aria-sort={key&&sort===key?(ascending?'ascending':'descending'):undefined}>{key?<button onClick={()=>sortBy(key)}>{label}{sort===key?(ascending?<ArrowUp size={12}/>:<ArrowDown size={12}/>):<ArrowDown size={11} className="sort-muted"/>}</button>:label}</th>)}</tr></thead><tbody>{visible.map((c,i)=>{const a=c.analytics[period],m=a?.metrics,currency=c.currency||(c.market==='GB'?'GBP':'USD');const isSaved=saved.some(s=>s.market===c.market&&s.username===c.username);return <tr key={`${c.market}-${c.username}`}><td>{(currentPage-1)*size+i+1}</td><td><button className="directory-creator" onClick={()=>onOpen(c,period)}>{safeUrl(c.avatar)?<img src={safeUrl(c.avatar)} alt=""/>:<span>{c.username[0].toUpperCase()}</span>}<div><strong>@{c.username}</strong><small>{c.displayName||'—'}</small><em>{c.niche||'Category —'}</em></div></button></td><td className="revenue-cell">{money(m?.revenue,currency)}</td><td>{number(m?.itemsSold)}</td><td>{number(c.followers)}</td><td>{number(m?.growth,'%')}</td><td><div className="directory-products">{a?.products.slice(0,3).map(p=>safeUrl(p.image)?<img key={p.id} src={safeUrl(p.image)} alt={p.name} title={p.name}/>:<span key={p.id} title={p.name}><Package size={16}/></span>)}{!a?.products.length&&'—'}</div></td><td><Trend creator={c} period={period}/></td><td>{number(m?.views)}</td><td>{number(m?.engagementRate,'%')}</td><td><div className="directory-row-actions"><button onClick={()=>onSave(c)} aria-label={isSaved?`Unsave ${c.username}`:`Save ${c.username}`}><Bookmark size={16} fill={isSaved?'currentColor':'none'}/></button><button onClick={()=>onOpen(c,period)}>View Analytics <ArrowUpRight size={13}/></button></div></td></tr>;})}</tbody></table></div>
    {!visible.length&&<div className="directory-table-empty" role="status"><span>{status==='loading'?<LoaderCircle className="spin" size={25}/>:<Users size={26} strokeWidth={1.4}/>}</span><h2>{status==='loading'?'Searching creator data...':status==='market_mismatch'?`No creator found in ${market?markets[market].name:''}`:status==='not_found'?'No creator found. Check the username and selected market.':error?'Unable to load creator data. Please try again.':status==='found'?'No creators match these filters':!market?'Choose your market to explore creators':'Your creator research starts here'}</h2><p>{error?error:status==='found'?'Try widening your filters or switching back to all creators.':status==='market_mismatch'?'This creator belongs to a different market. Switch country and search again.':!market?'Select a country above. Every result stays within that TikTok Shop market.':'Search a creator name, @username, or TikTok profile URL.'}</p>{error&&<button onClick={()=>search()}>Try again <ChevronRight size={13}/></button>}<div className="directory-empty-columns"><span>Audience</span><span>Shop performance</span><span>Product insights</span></div></div>}
    <div className="directory-pagination"><span>{filtered.length?`${filtered.length} matching creators on page ${currentPage}`:'No results loaded'}</span><div><select aria-label="Creators per page" value={size} onChange={e=>{setSize(Number(e.target.value));if(status==='found'||status==='not_found')search(applied,1,Number(e.target.value));}}><option value={10}>10 / page</option><option value={20}>20 / page</option><option value={50}>50 / page</option></select><button aria-label="Previous page" disabled={currentPage<=1||status==='loading'} onClick={()=>search(applied,currentPage-1)}><ChevronLeft size={15}/></button><b>{currentPage}</b><button aria-label="Next page" disabled={!hasMore||status==='loading'} onClick={()=>search(applied,currentPage+1)}><ChevronRight size={15}/></button></div></div></section></div><p className="directory-disclaimer">Revenue and sales are estimates where supplied. Unavailable metrics appear as —.</p></div>;
}

