export * from "./types/editorTypes";

export declare const DEFAULT_SHORTCUTS: Readonly<Record<string, string>>;
export declare function normalizeShortcut(eventOrString: KeyboardEvent | string): string;
export declare function createShortcutState(custom?: Record<string, string>): Record<string, string>;
export declare function actionForShortcut(shortcuts: Record<string, string>, shortcut: string): string | null;
export declare function createRafScheduler(task: (...args: unknown[]) => void): { request: (...args: unknown[]) => void; flush: (...args: unknown[]) => void };
export declare function timelineViewportWindow(input: { scrollLeft?: number; clientWidth?: number; unit?: number; bufferSeconds?: number }): { start: number; end: number };
export declare function isClipInWindow(clip: { timelineStart?: number; start?: number; duration?: number }, window: { start: number; end: number }): boolean;
export declare function runWhenIdle(task: IdleRequestCallback | TimerHandler, timeout?: number): number;
export declare function createFrameCache(limit?: number): { get(key: string): unknown | null; set(key: string, value: unknown): unknown; clear(): void };
export declare const PLUGIN_PERMISSIONS: readonly string[];
export declare const DEFAULT_PLUGIN_MARKETPLACE: readonly Record<string, unknown>[];
export declare function normalizePluginManifest(input?: Record<string, unknown>): Record<string, unknown>;
export declare function createPluginState(input?: { marketplace?: Record<string, unknown>[]; installed?: Record<string, unknown>[]; registry?: Record<string, unknown>[]; events?: Record<string, unknown>[] }): Record<string, unknown>;
export declare const ERROR_SEVERITY: readonly string[];
export declare const ERROR_SOURCE: readonly string[];
export declare function createErrorState(input?: Record<string, unknown>): Record<string, unknown>;
export declare function normalizeError(error: Error | string, context?: Record<string, unknown>): Record<string, unknown>;
export declare function logEditorError(state: Record<string, unknown>, error: Error | string, context?: Record<string, unknown>): Record<string, unknown>;
export declare function createRecoveryPoint(state: Record<string, unknown>, snapshot: Record<string, unknown>, reason?: string): Record<string, unknown>;
export declare function scanMissingMedia(clips?: Record<string, unknown>[], assets?: Record<string, unknown>[]): Record<string, unknown>[];
export declare const DRAG_TYPES: readonly string[];
export declare function normalizeDragPayload(input?: Record<string, unknown>): Record<string, unknown>;
export declare function canDropPayloadOnTrack(payload: Record<string, unknown>, track: Record<string, unknown>): boolean;
export declare function createDragSession(payload: Record<string, unknown>, now?: number): Record<string, unknown>;
export declare function createBackgroundQueue(input?: Record<string, unknown>): Record<string, unknown>;
export declare function createProjectSyncManager(input?: Record<string, unknown>): Record<string, unknown>;
export declare function createUploadManager(input?: Record<string, unknown>): Record<string, unknown>;
export declare function createDownloadManager(input?: Record<string, unknown>): Record<string, unknown>;
export declare function createConflictResolver(input?: Record<string, unknown>): Record<string, unknown>;
export declare function createOfflineMode(input?: Record<string, unknown>): Record<string, unknown>;

export interface EditorCoreOptions {
  fps?: number;
  duration?: number;
}

export declare class EditorCore {
  constructor(options?: EditorCoreOptions);
  state: any;
  subscribe(listener: (event: { event: string; payload: unknown; state: any }) => void): () => void;
  hydrateFromDom(root?: Document): void;
  setProjectMetadata(patch?: Partial<import("./types/editorTypes").ProjectRecord>): void;
  addAsset(asset?: Partial<import("./types/editorTypes").MediaAsset>): import("./types/editorTypes").MediaAsset;
  updateAsset(assetId: string, patch?: Partial<import("./types/editorTypes").MediaAsset>): unknown;
  deleteAssets(assetIds?: string[]): unknown;
  selectAsset(assetId: string, options?: { additive?: boolean; range?: boolean }): void;
  setAssetFilter(patch?: Partial<import("./types/editorTypes").AssetManagerState["filter"]>): void;
  filteredAssets(): import("./types/editorTypes").MediaAsset[];
  toggleAssetFavorite(assetIds?: string[]): unknown;
  tagAssets(assetIds?: string[], tag?: string): unknown;
  moveAssetsToFolder(assetIds?: string[], folder?: string): unknown;
  addTrack(track?: Partial<import("./types/editorTypes").TimelineTrack>): import("./types/editorTypes").TimelineTrack;
  addClip(clip?: Partial<import("./types/editorTypes").TimelineClip>): import("./types/editorTypes").TimelineClip | undefined;
  selectClip(id: string, options?: { additive?: boolean; range?: boolean }): void;
  clearSelection(): void;
  moveClip(id: string, nextStart: number, options?: { trackId?: string | null; ripple?: boolean }): unknown;
  moveClipToTrack(id: string, trackId: string, nextStart?: number | null): unknown;
  reorderClip(id: string, nextLayer: number): unknown;
  trimClipStart(id: string, nextStart: number, options?: { ripple?: boolean }): unknown;
  trimClipEnd(id: string, nextDuration: number, options?: { ripple?: boolean }): unknown;
  splitSelected(time?: number): unknown;
  duplicateSelected(offset?: number): unknown;
  deleteSelected(options?: { ripple?: boolean }): unknown;
  copySelected(): void;
  paste(time?: number): unknown;
  groupSelected(): unknown;
  setTrackState(trackId: string, patch: Partial<import("./types/editorTypes").TimelineTrack>): unknown;
  setTrackAudio(trackId: string, patch: { muted?: boolean; solo?: boolean }): unknown;
  seek(time: number): void;
  step(frames?: number): void;
  setPlaying(playing: boolean): void;
  setPlaybackRate(rate: number): void;
  setCanvasZoom(zoom: number): void;
  tick(now?: number): number;
  setZoom(zoom: number): void;
  transformSelected(patch: Partial<import("./types/editorTypes").ClipTransform>): unknown;
  setMotionControls(patch: Partial<import("./types/editorTypes").ClipTransform>): unknown;
  setSpeed(speed: number): unknown;
  reverseSelected(): unknown;
  freezeFrameSelected(time?: number): unknown;
  setOpacity(opacity: number): unknown;
  setBlendMode(blendMode: import("./types/editorTypes").BlendMode): unknown;
  addKeyframe(property: string, value: unknown, time?: number, easing?: string): unknown;
  selectKeyframe(id: string, options?: { additive?: boolean }): void;
  deleteSelectedKeyframes(): unknown;
  moveSelectedKeyframes(deltaSeconds: number): unknown;
  copySelectedKeyframes(): void;
  pasteKeyframes(time?: number): unknown;
  addTransition(type: "video" | "audio", duration?: number, name?: string, direction?: string): unknown;
  updateTransition(transitionId: string, patch: Record<string, unknown>): unknown;
  removeTransition(transitionId: string): unknown;
  duplicateTransition(transitionId: string): unknown;
  setAudio(patch: Partial<import("./types/editorTypes").AudioEnvelope>): unknown;
  setMute(muted?: boolean): unknown;
  setSolo(solo?: boolean): unknown;
  setAudioEQ(band: "low" | "mid" | "high", value: number): unknown;
  setAudioCompressor(patch?: Partial<NonNullable<import("./types/editorTypes").AudioEnvelope["compressor"]>>): unknown;
  setAudioLimiter(patch?: Partial<NonNullable<import("./types/editorTypes").AudioEnvelope["limiter"]>>): unknown;
  addAudioKeyframe(parameter: string, value: unknown, time?: number, easing?: string): unknown;
  setEffect(type: string, parameters?: Record<string, unknown>, enabled?: boolean): unknown;
  addEffect(type: import("./types/editorTypes").EffectType, parameters?: Record<string, unknown>): unknown;
  updateEffect(effectId: string, patch?: Record<string, unknown>): unknown;
  setEffectEnabled(effectId: string, enabled: boolean): unknown;
  removeEffect(effectId: string): unknown;
  duplicateEffect(effectId: string): unknown;
  reorderEffect(effectId: string, direction: number): unknown;
  addEffectKeyframe(effectId: string, parameter: string, value: unknown, time?: number, easing?: string): unknown;
  setColorGrade(parameter: keyof import("./types/editorTypes").ColorGrade, value: number): unknown;
  applyColorGrade(patch: Partial<import("./types/editorTypes").ColorGrade>): unknown;
  resetColorGrade(): unknown;
  applyColorPreset(name: string): unknown;
  copyColorGrade(): void;
  pasteColorGrade(): unknown;
  addColorGradeKeyframe(parameter: keyof import("./types/editorTypes").ColorGrade, value: number, time?: number, easing?: string): unknown;
  setTextLayer(patch?: Partial<import("./types/editorTypes").TextLayer>): unknown;
  setTextKind(kind: import("./types/editorTypes").TextLayerKind): unknown;
  setTextStyle(parameter: keyof import("./types/editorTypes").TextStyle, value: unknown): unknown;
  setTextAnimation(animation: import("./types/editorTypes").TextAnimationName): unknown;
  applyTextTemplate(templateId: string): unknown;
  addTextKeyframe(parameter: keyof import("./types/editorTypes").TextStyle | "text", value: unknown, time?: number, easing?: string): unknown;
  selectedCaptionClips(): import("./types/editorTypes").TimelineClip[];
  setCaptionLayer(patch?: Partial<import("./types/editorTypes").CaptionLayer>): unknown;
  setCaptionTiming(start: number, duration: number): unknown;
  updateCaptionWord(wordId: string, patch?: Partial<import("./types/editorTypes").CaptionWord>): unknown;
  applyCaptionTemplate(templateId: string): unknown;
  replaceCaptions(search: string, replacement: string): unknown;
  addCaptionTrack(name?: string): import("./types/editorTypes").TimelineTrack;
  exportCaptions(format?: "srt" | "json"): string;
  setAiCommand(command?: string): void;
  updateAiTool(toolId: string, patch?: Partial<import("./types/editorTypes").AiToolState>): unknown;
  runAiTool(toolId: string, instruction?: string): unknown;
  setAiToolProcessing(toolId: string, progress?: number): void;
  clearAiQueue(): unknown;
  registerPlugin(manifest?: Record<string, unknown>): unknown;
  installMarketplacePlugin(pluginId: string): unknown;
  loadPlugin(pluginId: string): unknown;
  disablePlugin(pluginId: string): unknown;
  updatePluginSettings(pluginId: string, patch?: Record<string, unknown>): unknown;
  updatePluginPermissions(pluginId: string, permissions?: string[]): unknown;
  logError(error: Error | string, context?: Record<string, unknown>): Record<string, unknown>;
  clearErrorNotification(id: string): void;
  createRecoveryPoint(reason?: string): Record<string, unknown>;
  scanMissingMedia(): Record<string, unknown>[];
  estimateExport(settings?: Partial<import("./types/editorTypes").ExportSettings>): { settings: import("./types/editorTypes").ExportSettings; sizeEstimateMb: number; validation: { valid: boolean; errors: string[] } };
  queueExport(settings?: Partial<import("./types/editorTypes").ExportSettings>, projectName?: string): import("./types/editorTypes").ExportJob;
  updateExportProgress(jobId: string, progress: number, status?: import("./types/editorTypes").ExportStatus): void;
  completeExport(jobId: string): unknown;
  cancelExport(jobId: string): unknown;
  failExport(jobId: string, error?: string): unknown;
  setLayerOrder(id: string, layer: number): unknown;
  previewFrame(): import("./types/editorTypes").TimelineClip[];
  renderFrame(time?: number): import("./types/editorTypes").RenderFrame;
  undo(): void;
  redo(): void;
}
